---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by li.jun.
--- DateTime: 1/29/2018 5:01 PM
---

module(..., package.seeall)

require 'aliyuniotssl'
require 'misc'
require 'audio'
require 'pins'

PRODUCT_KEY = 'IgW98z2NGr4'
newsn = 'AjJnJOPk4m23FLn8VW4gxvYRnbhmawlE' --air800
-- newsn = "rWGfH1dLIkopM8j3CvzTma21N08HE1eY"  --watch
-- newsn = "fCWgxisAf0AgtGIPkIjqKyxbOldZpzjs"  --s5
-- newsn = "rWGfH1dLIkopM8j3CvzTma21N08HE1eY" --s6

PIN8 = {pin = pio.P0_1} --继电器
PIN7 = {pin = pio.P0_0} --连接指示灯
PIN9 = {pin = pio.P0_9} --签名请求指示灯
pins.set(false, PIN7)
local function pin29cb(v)
    print('pin29cb', v)
    print(misc.getimei())

    if v then
        aliyuniotssl.publish("/"..PRODUCT_KEY.."/"..misc.getimei().."/update","{\"target\":\"liweitest\",\"command\":\"ok\"}",1)
        pins.set(false, PIN9)
    end
end
--第29个引脚：GPIO_6；配置为中断；valid=1
PIN29 = {pin = pio.P0_6, dir = pio.INT, valid = 1, intcb = pin29cb}
pins.reg(PIN29)

local function print(...)
    _G.print('guide info -->', ...)
end

local function setsn()
    if misc.getsn() ~= newsn then
        misc.setsn(newsn)
    end
end

local function subackcb(usertag, result)
    print('subackcb:', usertag, result)
    pins.set(true, PIN7)
    audio.play(0, 'FILE', '/ldata/wel01.mp3', audiocore.VOL7)
end

local function pin8off()
    pins.set(false, PIN8)
end
local function rcvmessagecb(topic, payload, qos)
    print('rcvmessagecb:', topic, payload, qos)
    local tjsondata, result, errinfo = json.decode(payload)
    local voice
    if result then
        voice = tjsondata['voice']
    else
        print('json.decode error:', errinfo)
        return
    end
    --aliyuniotssl.publish("/"..PRODUCT_KEY.."/"..misc.getimei().."/update","device receive:"..payload,qos)

    if voice == "request" then
        pins.set(true, PIN9)
    elseif voice == "cancel" then
        pins.set(false, PIN9)
    elseif voice == 'tts' then
        tts = tjsondata['tts']
        audio.play(0, 'TTS', common.binstohexs(common.utf8toucs2(tts)), audiocore.VOL5)
    else
        audio.play(0, 'FILE', '/ldata/' .. voice .. '.mp3', audiocore.VOL7)
    end

    if voice == 'aws02' then
        pins.set(true, PIN8)
        sys.timer_start(pin8off, 5000)
    end
end

local function connectedcb()
    print('connectedcb')
    --订阅主题
    aliyuniotssl.subscribe(
        {
            {topic = '/' .. PRODUCT_KEY .. '/' .. misc.getimei() .. '/get', qos = 0},
            {topic = '/' .. PRODUCT_KEY .. '/' .. misc.getimei() .. '/get', qos = 1}
        },
        subackcb,
        'subscribegetopic'
    )
    --注册事件的回调函数，MESSAGE事件表示收到了PUBLISH消息
    aliyuniotssl.regevtcb({MESSAGE = rcvmessagecb})
end

local function connecterrcb(r)
    print('connecterrcb:', r)
    pins.set(false, PIN7)
end
audio.play(0, 'FILE', '/ldata/wel02.mp3', audiocore.VOL7)
--5秒后开始烧写sn
sys.timer_start(setsn, 5000)
aliyuniotssl.config(PRODUCT_KEY)
aliyuniotssl.regcb(connectedcb, connecterrcb)
