---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by li.jun.
--- DateTime: 1/29/2018 5:01 PM
---

module(...,package.seeall)

require"aliyuniotssl"
require"misc"
require"audio"
require"common"

PRODUCT_KEY = "0S9dtdoet7C"
newsn = "iYRmZ9fd2E0BnwiwxaP6oAxsUlETedls"  --air800
--newsn = "UdSfAzmAGfZ10ALLgHunHOhmIx5kouTQ"  --watch
local rdbuf = ""

local voiceList = {}

local function print(...)
    _G.print("guide info -->",...)
end

local function setsn()
    if misc.getsn() ~= newsn then
        misc.setsn(newsn)
    end
end

local function parse(data)
    if not data then return end

    local tail = string.find(data,string.char(0xEF))
    if not tail then return false,data end

    print("parse",common.binstohexs(data, " "))

    return true,string.sub(data,tail+1,-1)
end

local function proc(data)
    if not data or string.len(data) == 0 then return end
    --追加到缓冲区
    rdbuf = rdbuf..data

    local result,unproc
    unproc = rdbuf
    --根据帧结构循环解析未处理过的数据
    while true do
        result,unproc = parse(unproc)
        if not unproc or unproc == "" or not result then
            break
        end
    end
    rdbuf = unproc or ""
end

local function writeUart(s)
    print("write-->",common.binstohexs(s, " "))
    uart.write(1,s)
end

local function readUart()
    local data = ""
    while true do
        data = uart.read(1,"*l",0)
        if not data or string.len(data) == 0 then break end
        proc(data)
    end
end

local function subackcb(usertag,result)
    print("subackcb:",usertag,result)
    audio.play(0,"FILE","/ldata/welcome_2.mp3",audiocore.VOL7)
end

local function procVolume(volume)
    print("volume-->", volume)
    local command = "7EFF06060000"..common.binstohexs(string.char(volume)).."EF"
    local commandBins = common.hexstobins(command);
    writeUart(commandBins)
    print(common.binstohexs(commandBins, " "))
end

local function procStop(flag)
    print("stop flag-->", flag)
    if flag==0 then
        voiceList = {}
    elseif flag==1 then
        local command = "7EFF0615000000FEE6EF"
        local commandBins = common.hexstobins(command);
        print(common.binstohexs(commandBins, " "))
    elseif flag==2 then
        voiceList = {}
        local command = "7EFF0616000000FEE5EF"
        local commandBins = common.hexstobins(command);
        print(common.binstohexs(commandBins, " "))
    end

end

local function rcvmessagecb(topic,payload,qos)
    print("rcvmessagecb:",topic,payload,qos)
    --aliyuniotssl.publish("/"..PRODUCT_KEY.."/"..misc.getimei().."/update","device receive:"..payload,qos)
    --audio.play(0,"FILE","/ldata/" .. payload .. ".mp3",audiocore.VOL7)
    local tjsondata,result,errinfo = json.decode(payload)
    if result then
        procVolume(tjsondata["volume"])
        procStop(tjsondata["stop"])
        print("insert-->", tjsondata["insert"])
        print("play-->", json.encode(tjsondata["play"]))
        for key, value in ipairs(tjsondata["play"]) do
            print(key, value, tjsondata["play"][key])
            table.insert(voiceList,value);
        end
    else
        print("json.decode error",errinfo)
    end

    for key, value in ipairs(voiceList) do
        print(key, value)
    end
end

local function connectedcb()
    print("connectedcb")
    --订阅主题
    aliyuniotssl.subscribe({{topic="/"..PRODUCT_KEY.."/"..misc.getimei().."/get",qos=0}, {topic="/"..PRODUCT_KEY.."/"..misc.getimei().."/get",qos=1}}, subackcb, "subscribegetopic")
    --注册事件的回调函数，MESSAGE事件表示收到了PUBLISH消息
    aliyuniotssl.regevtcb({MESSAGE=rcvmessagecb})
end

local function connecterrcb(r)
    print("connecterrcb:",r)
end

audio.play(0,"FILE","/ldata/welcome_1.mp3",audiocore.VOL7)
sys.timer_start(setsn,5000)
aliyuniotssl.config(PRODUCT_KEY)
aliyuniotssl.regcb(connectedcb,connecterrcb)
sys.reguart(1,readUart)
uart.setup(1,115200,8,uart.PAR_NONE,uart.STOP_1)