---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by li.jun.
--- DateTime: 1/22/2018 9:11 AM
---

local tinsert,ssub,sbyte,schar,sformat,slen = table.insert,string.sub,string.byte,string.char,string.format,string.len

function binstohexs(bins,s)
    local hexs = ""

    if bins == nil or type(bins) ~= "string" then return nil,"nil input string" end

    for i=1,slen(bins) do
        hexs = hexs .. sformat("%02X",sbyte(bins,i)) ..(s==nil and "" or s)
    end
    hexs = string.upper(hexs)
    return hexs
end
function hexstobins(hexs)
    local tbins = {}
    local num

    if hexs == nil or type(hexs) ~= "string" then return nil,"nil input string" end

    for i=1,slen(hexs),2 do
        num = tonumber(ssub(hexs,i,i+1),16)
        if num == nil then
            return nil,"error num index:" .. i .. ssub(hexs,i,i+1)
        end
        tinsert(tbins,num)
    end

    return schar(unpack(tbins))
end
--print(binstohexs(10,""))
--print(binstohexs(tonumber(10),""))
--print(string.char(0x32))
--print(hexstobins("32"))
print(binstohexs(schar(15)))